Create issue templates
Thalhammer/jwt-cpp pull request #131
Opened 2021-01-30 19:48 UTC by prince-chrismc

2021-01-30 20:14 UTC, Thalhammer requested changes

2021-01-30 20:14 UTC, Thalhammer commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: "[bug] Breif Description"
Brief

2021-01-30 20:14 UTC, Thalhammer commented on .github/ISSUE_TEMPLATE/support-question.md
> +title: "[question] Breif Description"
Brief

2021-01-30 20:15 UTC, prince-chrismc commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: "[bug] Breif Description"
```suggestion
title: "[bug] Brief Description"
```

2021-01-30 20:19 UTC, prince-chrismc commented
I want to take a look for some other examples, this way it should be easier to resolve after 🤞

2021-01-31 12:33 UTC, Thalhammer approved these changes

2021-01-31 15:13 UTC, merged