Improved issue templates with security policy
Thalhammer/jwt-cpp pull request #217
Opened 2022-03-11 20:20 UTC by prince-chrismc

👋 looking to make the process easier for our growing community 

- please look at the security policy for the contact

2022-03-11 22:33 UTC, Thalhammer requested changes
I added my E-Mail to my github profile. It's already out there anyway if you crawl my commits so I might as well add it well visible. I'd rather not want people use the contact form since it tends to have a lot of spam on it and I'll probably remove it entirely when I redo my website (If that TODO ever happens...).

Otherwise it looks fine to me.

2022-03-13 22:59 UTC, prince-chrismc commented
That makes totally sense! I updated the contact method 👍

2022-03-14 13:55 UTC, Thalhammer approved these changes

2022-03-14 13:57 UTC, merged

2022-03-14 13:58 UTC, Thalhammer commented
Lets hope the security policy never becomes relevant....